apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qft
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: qft.1a074a4ade81432ea931.eastasia.aksapp.io
    http:
      paths:
      - path: /api/v1/
        pathType: Prefix
        backend:
          service: 
            name: qft-svc
            port: 
              number: 80
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service: 
            name: qft-auth-svc
            port: 
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: qft-client-svc
            port: 
              number: 80