_format_version: "1.1"

###
### API Routes
###
services:
  - name: goauth
    _comment: "GoAuth: /api/v1/auth -> http://go-auth-api:go-auth-api:8080/api/v1/auth"
    url: http://go-auth-api:8080/api/v1/auth/
    routes:
      - name: go-auth-v1-all
        strip_path: true
        paths:
          - /api/v1/auth/
    plugins:
      - name: cors

  - name: qft
    _comment: "QFT: /api/v1/qft -> http://go-auth-api:qft-api:8080/api/v1"
    url: http://qft-api:8081/api/v1/
    routes:
      - name: qft-v1-all
        strip_path: true
        paths:
          - /api/v1/qft/
    plugins:
      - name: cors
