# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - qft

on:
  push:
    branches:
      - azure-actions
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.AzureAppService_ContainerUsername_783b5b6308e84a6b965fdd640d047585 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8cc7a644ea964f81a5a767c45cfe7ec9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_783b5b6308e84a6b965fdd640d047585 }}/qft:${{ github.sha }}
        file: ./server/Dockerfile
        context: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'qft'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ccc7a731dcb74a25b9f77bf060821693 }}
        images: '${{ secrets.AzureAppService_ContainerUsername_783b5b6308e84a6b965fdd640d047585 }}/qft:${{ github.sha }}'